version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "monthly"

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    
  - package_manager: "docker"
    directory: "/"
    update_schedule: "monthly"
